# Generated by Django 2.2.7 on 2019-11-14 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsUp', '0002_auto_20191114_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by+', to=settings.AUTH_USER_MODEL),
        ),
    ]
